import { PaginatedResponse } from '@core/models/paginated-response.model';

export interface Animal {
  farmCode: number;
  animalCode: string;
  initialFatherCode: number | null;
  initialMotherCode: number | null;
  colorCode: number;
  hairTypeCode: number;
  cowshedCode: number | null;
  corralCode: number | null;
  corralLotCode: number | null;
  fatherFarmCode: number | null;
  fatherCode: number | null;
  breedCode: number;
  pastureCode: number | null;
  pastureLotCode: number | null;
  motherFarmCode: number | null;
  motherCode: number | null;
  embryoFarmCode: number | null;
  embryoCode: number | null;
  associationCode: number | null;
  farmId: string;
  electronicId: string;
  animalName: string;
  origin: string;
  breederCode: number | null;
  creatorId: number | null;
  tattoo: string;
  sex: string;
  birthDate: string;
  birthWeight: string;
  entryDate: string;
  status: string;
  bloodPercentage: string;
  bloodName: string;
  lastWeightDate: string;
  currentWeight: string;
  weaningDate: string;
  weaningWeight: string;
  originAssociationId: number | null;
  bodyConditionCode: number | null;
  registrationDate: string | null;
  breeder: string;
  nextReviewDate: string | null;
  classificationDate: string | null;
  finalClassification: string | null;
  classificationRegisterNumber: string | null;
  features: string;
  observations: string;
  photo: number;
  geneticIndex: string;
  geneticAverage: string;
  determinationIndex: string;
  daughtersGeneticIndex: string | null;
  farmsGeneticIndex: string | null;
  lactationsGeneticIndex: string | null;
  weightsIndex: string;
  weightsDetailIndex: string | null;
  daughtersWeightsIndex: string | null;
  farmsWeightsIndex: string | null;
  weighedWeightsIndex: string | null;
  precocityIndex: string;
  precocityDetailIndex: string | null;
  daughtersPrecocityIndex: string | null;
  farmsPrecocityIndex: string | null;
  weighedPrecocityIndex: string | null;
  heightIndex: string;
  heightDetailIndex: string | null;
  fvIndex: string;
  fvDetailIndex: string | null;
  acIndex: string;
  acDetailIndex: string | null;
  autIndex: string;
  autDetailIndex: string | null;
  ngIndex: string;
  ngDetailIndex: string | null;
  apIndex: string;
  apDetailIndex: string | null;
  iudIndex: string;
  iudDetailIndex: string | null;
  puIndex: string;
  puDetailIndex: string | null;
  npuIndex: string;
  npuDetailIndex: string | null;
  spdIndex: string;
  spdDetailIndex: string | null;
  ptIndex: string;
  ptDetailIndex: string | null;
  anIndex: string;
  anDetailIndex: string | null;
  iutIndex: string;
  iutDetailIndex: string | null;
  lmuIndex: string;
  lmuDetailIndex: string | null;
  lpIndex: string;
  lpDetailIndex: string | null;
  pcIndex: string;
  pcDetailIndex: string | null;
  projectId: number | null;
  internalNumber: string;
  internalCode: string;
  uniqueCode: string;
  weaningWeight75: string;
  weaningWeight150: string;
  conceptionType: string;
  currentFarmCode: number;
  bloodType: string;
  locationStatus: string;
  conditionStatus: string;
  leftEarTattoo: string;
  rightEarTattoo: string;
  tailTattoo: string;
  exitDate: string | null;
  weightAlert: string;
  fatherVariety: string;
  motherVariety: string;
  recipientVariety: string;
  fatherBreeder: string;
  motherBreeder: string;
  motherRegisterNumber: string;
  fatherRegisterNumber: string;
  extraRegisterInfo: string;
  fatherAssociationCode: string;
  motherAssociationCode: string;
  preClassificationCode: number;
  preClassificationDate: string;
  var1: string;
  var2: string;
  birthType: string;
  supernumeraryTeats: string;
  classificationStatus: string;
  mouthPigmentation: number;
  nosePigmentation: number;
  eyesPigmentation: number;
  earsPigmentation: number;
  perianalAreaPigmentation: number;
  vulvaPigmentation: number;
  rafNumber: number;
  rafCode: string;
  impProtocol: string;
  geneticMaterialType: string;
  oldAssociation: string;
  testAssociation: string;
  fatherAssociation: string;
  motherAssociation: string;
  fatherTestAssociation: string;
  motherTestAssociation: string;
  totalPigmentation: number;
  trial660: string;
  image: string;
} 