export interface AnimalDto {
  cod_finca: string;
  cod_animal: string;
  nomb_animal: string;

  sexo_animal: string;
  fec_nacim: string;
  peso_al_nacer: string;
  fec_ingreso: string;
  estatus: string;
  peso_actual: string;
  cod_raza: string;
  cod_color: string;
  cod_tipo_pelo: number;
  observac: string;
  cod_ini_porsan_pa: number | null;
  cod_ini_porsan_ma: number | null;
  cod_vaquera: number | null;
  cod_corral: number | null;
  cod_lote_corral: number | null;
  cod_finca_padre: number | null;
  cod_padre: number | null;
  cod_potrero: number | null;
  cod_lote_potrero: number | null;
  cod_finca_madre: number | null;
  cod_madre: number | null;
  cod_finca_embrion: number | null;
  cod_embrion: number | null;
  cod_asociacion: number | null;
  cod_criador: number | null;
  id_creador: number | null;
  tatuaje: string;
  porcen_sangre: string;
  nomb_sangre: string;
  fec_ult_peso: string;
  fec_destete: string;
  peso_destete: string;

  cod_cond_corporal: number | null;
  fec_registro: string | null;
  reproductor: string;
  fec_prox_revision: string | null;
  fecha_clasificacion: string | null;
  clasificacion_defin: string | null;
  nro_registro_cla: string | null;
  caracteristicas: string;
  foto: number;
  ind_genetico: string;
  prom_genetico: string;
  ind_determinacion: string;
  ind_genetico_hijas: string | null;
  ind_genetico_fincas: string | null;
  ind_genetico_lactancias: string | null;
  ind_pesos: string;
  ind_det_pesos: string | null;
  ind_pesos_hijas: string | null;
  ind_pesos_fincas: string | null;
  ind_pesos_pesadas: string | null;
  ind_precocidad: string;
  ind_det_precocidad: string | null;
  ind_precocidad_hijas: string | null;
  ind_precocidad_fincas: string | null;
  ind_precocidad_pesadas: string | null;
  ind_alz: string;
  ind_det_alz: string | null;
  ind_fv: string;
  ind_det_fv: string | null;
  ind_ac: string;
  ind_det_ac: string | null;
  ind_aut: string;
  ind_det_aut: string | null;
  ind_ng: string;
  ind_det_ng: string | null;
  ind_ap: string;
  ind_det_ap: string | null;
  ind_iud: string;
  ind_det_iud: string | null;
  ind_pu: string;
  ind_det_pu: string | null;
  ind_npu: string;
  ind_det_npu: string | null;
  ind_spd: string;
  ind_det_spd: string | null;
  ind_pt: string;
  ind_det_pt: string | null;
  ind_an: string;
  ind_det_an: string | null;
  ind_iut: string;
  ind_det_iut: string | null;
  ind_lmu: string;
  ind_det_lmu: string | null;
  ind_lp: string;
  ind_det_lp: string | null;
  ind_pc: string;
  ind_det_pc: string | null;
  id_pro: number | null;
  numero_interno: string;
  codigo_interno: string;
  codigo_unico: string;
  peso_destete_75: string;
  peso_destete_150: string;
  tipo_concepcion: string;
  cod_finca_actual: number;
  p_sangre: string;
  estatus_ubicacion: string;
  estatus_condicion: string;
  tatuaje_oreja_izq: string;
  tatuaje_oreja_der: string;
  tatuaje_cola: string;
  fec_egreso: string | null;
  alerta_peso: string;
  var_padre: string;
  var_madre: string;
  var_receptora: string;
  cri_padre: string;
  cri_madre: string;
  nro_reg_madre: string;
  nro_reg_padre: string;
  info_extra_reg: string;
  cod_aso_padre: string;
  cod_aso_madre: string;
  cod_pre_clasif: number;
  fec_pre_clasif: string;
  var_1: string;
  var_2: string;
  tipo_parto: string;
  pezones_supernumerarios: string;
  estatus_clasif: string;
  pigmen_boca: number;
  pigmen_nariz: number;
  pigmen_ojos: number;
  pigmen_orejas: number;
  pigmen_area_perianal: number;
  pigmen_vulva: number;
  nro_raf: number;
  codigo_raf: string;
  protocolo_imp: string;
  tipo_material_gen: string;
  old_aso: string;
  pru_aso: string;
  padre_aso: string;
  madre_aso: string;
  pru_aso_padre: string;
  pru_aso_madre: string;
  pigmen_total: number;
  trial660: string;
  imagen: string;
} 